name: Stan Lee
author: Stan Lee
baseurl: ""
description: stanlee's homepage
github: http://www.github.com/stanlee5
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: stanleee5[at]google.com
location: 37°17'45.9"N 126°58'23.0"E
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
